version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.8-alpine
    container_name: clickhouse
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - default
    ports:
      - "8123:8123"

  analytics:
    container_name: analytics
    build: ./packages/analytics
    ports:
      - "9000:9000"
    depends_on:
      - clickhouse
    environment:
      - PORT=9000
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    networks:
      - default

volumes:
  event-data:
    driver: local
