version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.8-alpine
    container_name: clickhouse
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - default
    ports:
      - "8123:8123"

  rabbitmq:
    image: 'rabbitmq:3.11-management'
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_DEFAULT_VHOST: '/'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rabbitmq_network

  # analytics:
  #   container_name: analytics
  #   build: ./packages/analytics
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - clickhouse
  #   environment:
  #     - PORT=9000
  #     - CLICKHOUSE_HOST=clickhouse
  #     - CLICKHOUSE_PORT=8123
  #   networks:
  #     - default

  # embeddings:
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   build: ./packages/embeddings
  #   ports:
  #     - "5000-5003:5000"
  #   networks:
  #     - rabbitmq_network

volumes:
  event-data:
    driver: local
networks:
  rabbitmq_network:
    name: rabbitmq_network
